package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"time"
)

func cmdSSHConfig() {
	cache := getCache()
	ensureCache(cache)
	instances, err := cache.Load()
	fatal(err, "load cache")

	config := mustLoadConfig()

	fmt.Println("# Generated by tssh ssh-config")
	fmt.Printf("# Profile: %s, Region: %s\n", config.ProfileName, config.Region)
	fmt.Printf("# %d instances, %s\n\n", len(instances), time.Now().Format("2006-01-02 15:04:05"))

	for _, inst := range instances {
		if inst.Status != "Running" {
			continue
		}
		fmt.Printf("Host %s\n", inst.Name)
		fmt.Printf("  HostName %s\n", inst.PrivateIP)
		fmt.Printf("  User root\n")
		fmt.Printf("  # InstanceID: %s\n", inst.ID)
		fmt.Printf("  # Use: tssh %s\n\n", inst.Name)
	}
}

// cmdProfiles lists available profiles
func cmdProfiles() {
	profiles := ListProfiles()
	if len(profiles) == 0 {
		fmt.Println("没有找到配置的账号")
		return
	}
	// Resolve which profile is actually active: explicit --profile wins,
	// otherwise ask config.Load to pick (env > default > first config entry).
	// Previously marked BOTH "default" and "env" when globalProfile=="" which
	// was confusing — only one is actually used.
	active := globalProfile
	if active == "" {
		if cfg, err := LoadConfigWithProfile(""); err == nil {
			active = cfg.ProfileName
		}
	}
	fmt.Println("可用账号:")
	for _, p := range profiles {
		marker := "  "
		if p == active {
			marker = "→ "
		}
		fmt.Printf("  %s%s\n", marker, p)
	}
}

// cmdHistory shows recent exec history
func cmdHistory() {
	cache := getCache()
	histFile := filepath.Join(cache.HistoryDir(), "history.json")
	data, err := os.ReadFile(histFile)
	if err != nil {
		fmt.Println("暂无执行历史")
		return
	}

	var entries []historyEntry
	json.Unmarshal(data, &entries)

	// Show last 20
	start := 0
	if len(entries) > 20 {
		start = len(entries) - 20
	}
	for _, e := range entries[start:] {
		fmt.Printf("[%s] %d台 → %s\n", e.Time, e.TargetCount, truncateStr(e.Command, 60))
	}
}

type historyEntry struct {
	Time        string `json:"time"`
	Command     string `json:"command"`
	TargetCount int    `json:"target_count"`
	Profile     string `json:"profile,omitempty"`
}

func saveHistory(command string, results interface{}) {
	cache := getCache()
	histFile := filepath.Join(cache.HistoryDir(), "history.json")

	var entries []historyEntry
	if data, err := os.ReadFile(histFile); err == nil {
		json.Unmarshal(data, &entries)
	}

	// Use reflection via reflect.ValueOf to get length — avoids JSON re-encoding
	// which costs O(payload) for a single int. Falls back to 0 if not slice-like.
	count := 0
	v := reflect.ValueOf(results)
	if v.IsValid() && (v.Kind() == reflect.Slice || v.Kind() == reflect.Array) {
		count = v.Len()
	}

	entries = append(entries, historyEntry{
		Time:        time.Now().Format("2006-01-02 15:04:05"),
		Command:     command,
		TargetCount: count,
		Profile:     globalProfile,
	})

	// Keep last 1000 entries
	if len(entries) > 1000 {
		entries = entries[len(entries)-1000:]
	}

	cache.Ensure()
	data, _ := json.Marshal(entries)
	// 0600: history records every command run on every ECS — often contains
	// prod paths, internal IPs, sometimes tokens in command args.
	// Atomic write: Ctrl-C mid-save shouldn't leave a corrupt history.
	tmp := histFile + ".tmp"
	if err := os.WriteFile(tmp, data, 0600); err == nil {
		os.Rename(tmp, histFile)
	}
}

// --- Symlink tools ---

func cmdCompletion() {
	shell := os.Getenv("SHELL")
	exe, _ := os.Executable()

	if strings.Contains(shell, "zsh") {
		fmt.Printf(`# 添加到 ~/.zshrc:
_tssh() {
  local -a instances
  instances=(${(f)"$(%s --complete)"})
  _describe 'instances' instances
}
compdef _tssh tssh
compdef _tssh tscp
compdef _tssh trsync
# v1.17+ slim binaries share the same instance list
compdef _tssh tssh-k8s
compdef _tssh tssh-net
compdef _tssh tssh-arms
compdef _tssh tssh-db
`, exe)
	} else {
		fmt.Printf(`# 添加到 ~/.bashrc:
_tssh() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  COMPREPLY=($(compgen -W "$(%s --complete)" -- "$cur"))
}
complete -F _tssh tssh
complete -F _tssh tscp
complete -F _tssh trsync
# v1.17+ slim binaries share the same instance list
complete -F _tssh tssh-k8s
complete -F _tssh tssh-net
complete -F _tssh tssh-arms
complete -F _tssh tssh-db
`, exe)
	}
}

func cmdComplete() {
	cache := getCache()
	instances, err := cache.Load()
	if err != nil {
		return
	}
	for _, inst := range instances {
		if inst.Name != "" {
			fmt.Println(inst.Name)
		}
	}
}
